### ISSUE TITLE
#BUG Windows installation

### ISSUE THREAD

**Issue by devstorm321** [vstconsulting/vstutils#18]
#BUG

While installing vstutils on windows 10, an error occurred.
os.uname should be replaced platform.uname().

`    ERROR: Command errored out with exit status 1:
     command: 'e:\python\vstutils\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A\\AppData\\Local\\Temp\\pip-install-kx2mdh40\\uwsgi\\setup.py'"'"'; __file__='"'"'C:\\Users\\A\\AppData\\Local\\Temp\\pip-install-kx2mdh40\\uwsgi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\A\AppData\Local\Temp\pip-pip-egg-info-uv2dczl5'
         cwd: C:\Users\A\AppData\Local\Temp\pip-install-kx2mdh40\uwsgi\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\A\AppData\Local\Temp\pip-install-kx2mdh40\uwsgi\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "C:\Users\A\AppData\Local\Temp\pip-install-kx2mdh40\uwsgi\uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: module 'os' has no attribute 'uname'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by devstorm321** [comment]
@onegreyonewhite Can I contribute to this project?

**Comment by onegreyonewhite** [comment]
> @onegreyonewhite Can I contribute to this project?

Yes, of course. But we are developing on the Gitlab platform. This is just a mirror.

> While installing vstutils on windows 10

We does not support MS Windows. Look at `classifiers`.

> C:\Users\A\AppData\Local\Temp\pip-install-kx2mdh40\uwsgi\uwsgiconfig.py", line 8, in <module> uwsgi_os = os.uname()[0] AttributeError: module 'os' has no attribute 'uname'

As you can see, the problem is that you cannot build uwsgi, which is used as a server. That's why we do not support MS Windows.

**Comment by devstorm321** [comment]
@onegreyonewhite How can I contribute? I can not find this project in Gitlab

**Comment by onegreyonewhite** [comment]
> @onegreyonewhite How can I contribute? I can not find this project in Gitlab

Like github - https://gitlab.com/vstconsulting/vstutils
